name: Model Deployment
on: 
  push:
    branches: [ main ]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Deploy in hike-and-seek cloud
        uses: hashicorp/setup-terraform@v1
      - run: terraform init
      - run: terraform plan
      - run: terraform apply -auto-approve 

            




