name: Model Deployment
on: 
  repository_dispatch:
    types: [deploy-event]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy in hike-and-seek cloud
        uses: hashicorp/setup-terraform@v1
     
      - run: terraform init
      - run: terraform plan 
      - run: terraform apply -auto-approve 

            




